CREATE TABLE users (
                       id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR2(255) NOT NULL UNIQUE,
                       birth_date DATE,
                       password_hash VARCHAR2(255) NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_analysis_settings (
                                        user_id NUMBER(19) PRIMARY KEY,
                                        frame_interval NUMBER(10) DEFAULT 30,
                                        notification_enabled NUMBER(1) DEFAULT 1,
                                        CONSTRAINT fk_user_analysis_settings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE video (
                       id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id NUMBER(19) NOT NULL,
                       filename VARCHAR2(255) NOT NULL,
                       original_filename VARCHAR2(255),
                       upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       CONSTRAINT fk_video_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE feature (
                         id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         video_id NUMBER(19) NOT NULL,
                         frame_number NUMBER(10),
                         landmarks CLOB,
                         "TIMESTAMP" TIMESTAMP,
                         CONSTRAINT fk_feature_video FOREIGN KEY (video_id) REFERENCES video(id) ON DELETE CASCADE
);

CREATE TABLE video_tag (
                           id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           video_id NUMBER(19) NOT NULL,
                           tag_name VARCHAR2(255) NOT NULL,
                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                           CONSTRAINT fk_video_tag_video FOREIGN KEY (video_id) REFERENCES video(id) ON DELETE CASCADE
);

CREATE TABLE fall_detection (
                                id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                video_id NUMBER(19) NOT NULL,
                                is_fall_detected NUMBER(1) NOT NULL,
                                confidence FLOAT,
                                fall_frame_number NUMBER(10),
                                analysis_details CLOB,
                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                CONSTRAINT fk_fall_detection_video FOREIGN KEY (video_id) REFERENCES video(id) ON DELETE CASCADE
);

CREATE TABLE feature_fall_detection (
                                        feature_id NUMBER(19) NOT NULL,
                                        fall_detection_id NUMBER(19) NOT NULL,
                                        contribution_weight FLOAT,
                                        PRIMARY KEY (feature_id, fall_detection_id),
                                        CONSTRAINT fk_ffd_feature FOREIGN KEY (feature_id) REFERENCES feature(id) ON DELETE CASCADE,
                                        CONSTRAINT fk_ffd_fall_detection FOREIGN KEY (fall_detection_id) REFERENCES fall_detection(id) ON DELETE CASCADE
);
