-- Oracle-compatible DDL (H2 also accepts this syntax)
-- Note: Oracle does not support "IF NOT EXISTS"; remove it.
-- Oracle-safe, idempotent creation of APP_USER table and unique constraint.
-- Prevents ORA-00955 by checking existence before creating objects.

DECLARE
    v_cnt NUMBER;
BEGIN
    -- Create table if it doesn't exist
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'APP_USER';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE q'{
        CREATE TABLE APP_USER (
                                  ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                                  USERNAME VARCHAR2(255) NOT NULL,
                                  PASSWORD VARCHAR2(255) NOT NULL,
                                  BIRTH_DATE DATE,
                                  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  CONSTRAINT PK_APP_USER PRIMARY KEY (ID)
        )
        }';
    END IF;

    -- Add unique constraint on USERNAME if missing
    SELECT COUNT(*) INTO v_cnt FROM user_constraints WHERE table_name = 'APP_USER' AND constraint_name = 'UX_APP_USER_USERNAME';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE APP_USER ADD CONSTRAINT UX_APP_USER_USERNAME UNIQUE (USERNAME)';
    END IF;

    -- Ensure columns exist (for environments where table pre-existed with different shape)
    SELECT COUNT(*) INTO v_cnt FROM user_tab_cols WHERE table_name = 'APP_USER' AND column_name = 'BIRTH_DATE';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE APP_USER ADD (BIRTH_DATE DATE)';
    END IF;

    SELECT COUNT(*) INTO v_cnt FROM user_tab_cols WHERE table_name = 'APP_USER' AND column_name = 'CREATED_AT';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE APP_USER ADD (CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP)';
    END IF;

    SELECT COUNT(*) INTO v_cnt FROM user_tab_cols WHERE table_name = 'APP_USER' AND column_name = 'UPDATED_AT';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE APP_USER ADD (UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP)';
    END IF;
END;
/
