DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'VIDEO_FILE';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE q'{
            CREATE TABLE VIDEO_FILE (
                ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                USER_ID NUMBER(19) NOT NULL,
                STORED_FILENAME VARCHAR2(255) NOT NULL,
                ORIGINAL_FILENAME VARCHAR2(255),
                TITLE VARCHAR2(255),
                DESCRIPTION VARCHAR2(2000),
                FILE_SIZE NUMBER(19),
                CONTENT_TYPE VARCHAR2(255),
                STORAGE_PATH VARCHAR2(1000),
                UPLOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT FK_VIDEO_FILE_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID) ON DELETE CASCADE
            )
        }';
    END IF;

    -- Ensure important columns exist (handles environments where table was created manually)
    FOR col_name IN (SELECT 'STORED_FILENAME' AS name FROM dual UNION ALL
                     SELECT 'ORIGINAL_FILENAME' FROM dual UNION ALL
                     SELECT 'TITLE' FROM dual UNION ALL
                     SELECT 'DESCRIPTION' FROM dual UNION ALL
                     SELECT 'CONTENT_TYPE' FROM dual UNION ALL
                     SELECT 'STORAGE_PATH' FROM dual)
    LOOP
        SELECT COUNT(*) INTO v_cnt FROM user_tab_cols WHERE table_name = 'VIDEO_FILE' AND column_name = col_name.name;
        IF v_cnt = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE VIDEO_FILE ADD ' || col_name.name || ' VARCHAR2(255)';
        END IF;
    END LOOP;

    SELECT COUNT(*) INTO v_cnt FROM user_tab_cols WHERE table_name = 'VIDEO_FILE' AND column_name = 'FILE_SIZE';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE VIDEO_FILE ADD FILE_SIZE NUMBER(19)';
    END IF;

    SELECT COUNT(*) INTO v_cnt FROM user_tab_cols WHERE table_name = 'VIDEO_FILE' AND column_name = 'UPLOAD_DATE';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE VIDEO_FILE ADD UPLOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP';
    END IF;

    SELECT COUNT(*) INTO v_cnt FROM user_tab_cols WHERE table_name = 'VIDEO_FILE' AND column_name = 'UPDATED_AT';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE VIDEO_FILE ADD UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP';
    END IF;

    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE table_name = 'VIDEO_FILE' AND index_name = 'IDX_VIDEO_FILE_USER';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_VIDEO_FILE_USER ON VIDEO_FILE(USER_ID)';
    END IF;
END;
/
